## -*- encoding: utf-8 -*-

# This file was *autogenerated* from the file PreAlgebraCourse.sagetex.sage
from sage.all_cmdline import *   # import sage library

## This file (PreAlgebraCourse.sagetex.sage) was *autogenerated* from PreAlgebraCourse.tex with sagetex.sty version 2015/08/26 v3.0-92d9f7a.
import sagetex
_st_ = sagetex.SageTeXProcessor('PreAlgebraCourse', version='2015/08/26 v3.0-92d9f7a', version_check=True)

